apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        grafana: running
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
      