apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  namespace: web
  labels:
    function: mydaemonset
spec:
  selector:
    matchLabels:
      pod: daemonset-pod
  template: 
    metadata:
      labels:
        pod: daemonset-pod
    spec:
      nodeSelector:
        test: passed
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi" #megabytes, how much memory space to add
            cpu: "250m" #how much cpy memory to add
        ports:
        - containerPort: 80