apiVersion: v1
kind: Service
metadata:
  name: clusterip
  namespace: web #should be in the same namespace of deployment
spec:
  selector:
    app: nginx #matches the key:value pair of the target pods
  ports:
    - protocol: TCP
      port: 80 #service's port
      targetPort: 80 #pod's port
  type: ClusterIP #for internal communication