apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::654654231423:role/tfnodegrouprole
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::654654231423:user/pablo
      username: pablo
      groups: []
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

  #userarn (line 10) gets tied to a kubernetes username (line 11)