apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: web
  labels: #could be any label
    type: deployment
spec:
  replicas: 2 #how many pods to create
  selector:
    matchLabels: #manage pods with nginx resources
      app: nginx #finds label with nginx
  template: #what pod we are creating, ex: nginx
    metadata:ku
      labels:
        app: nginx
    spec: #specs for containers to execute in the pod
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi" #megabytes, how much memory space to add
            cpu: "250m" #how much cpy memory to add
        ports:
        - containerPort: 80