apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: web
spec:
  storageClassName: "nginx-sc" #must match the name of the storage class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
