apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: web
  labels: #could be any label
    type: deployment
spec: #specification of the pods
  replicas: 2 #how many pods to create
  selector:
    matchLabels: #manage pods with nginx resources
      app: nginx #finds label with nginx
  template: #what pod we are creating, ex: nginx
    metadata:
      labels:
        app: nginx #label of pods
    spec: #specs for containers to execute in the pod
      nodeSelector:
        topology.kubernetes.io/zone: us-west-1c
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts: #
        - name: nginx-pv
          mountPath: /usr/share/nginx/html/ #path that your volume will be mounted to
      volumes: #selects the pvc
      - name: nginx-pv #can be anything
        persistentVolumeClaim:
          claimName: nginx-pvc #must match the pvc