apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-ns-binding
  namespace: web
subjects:
- kind: User
  name: k8tfuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin-ns #must match role
  apiGroup: rbac.authorization.k8s.io